<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer shopID
 * - integer itemID
 * - integer cash
 * - integer favours
 * - integer kudos
 *
 * - Item item
 * - Shop shop
 * <br>
 * <p>This is the model base class for the table "{{shop_items}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopItems".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseShopItems extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{shop_items}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'ShopItems|ShopItems', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('shopID, itemID', 'required'),
			array('shopID, itemID, cash, favours, kudos', 'numerical', 'integerOnly'=>true),
			array('cash, favours, kudos', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, shopID, itemID, cash, favours, kudos', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'item' => array(self::BELONGS_TO, 'Item', 'itemID'),
			'shop' => array(self::BELONGS_TO, 'Shop', 'shopID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'shopID' => null,
			'itemID' => null,
			'cash' => Yii::t('app', 'Cash'),
			'favours' => Yii::t('app', 'Favours'),
			'kudos' => Yii::t('app', 'Kudos'),
			'item' => null,
			'shop' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('shopID', $this->shopID);
		$criteria->compare('itemID', $this->itemID);
		$criteria->compare('cash', $this->cash);
		$criteria->compare('favours', $this->favours);
		$criteria->compare('kudos', $this->kudos);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}