<?php

/**
 * This is the model base class for the table "{{character_skills}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterSkills".
 *
 * Columns in table "{{character_skills}}" available as properties of the model,
 * followed by relations of table "{{character_skills}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $characterID
 * @property integer $skillID
 * @property integer $available
 * @property integer $permed
 *
 * @property Skill $skill
 * @property Character $character
 */
abstract class BaseCharacterSkills extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{character_skills}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CharacterSkills|CharacterSkills', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('characterID, skillID, available', 'required'),
			array('characterID, skillID, available, permed', 'numerical', 'integerOnly'=>true),
			array('permed', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, skillID, available, permed', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'skill' => array(self::BELONGS_TO, 'Skill', 'skillID'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'skillID' => null,
			'available' => Yii::t('app', 'Available'),
			'permed' => Yii::t('app', 'Permed'),
			'skill' => null,
			'character' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('skillID', $this->skillID);
		$criteria->compare('available', $this->available);
		$criteria->compare('permed', $this->permed);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}