<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer familiarID
 * - integer active
 * - string name
 * - integer xp
 *
 * - Character character
 * <br>
 * <p>This is the model base class for the table "{{character_familiars}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterFamiliars".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterFamiliars extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_familiars}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterFamiliars|CharacterFamiliars', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'name';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, familiarID, active, name', 'required'),
			array('characterID, familiarID, active, xp', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('xp', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, familiarID, active, name, xp', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'familiarID' => Yii::t('app', 'Familiar'),
			'active' => Yii::t('app', 'Active'),
			'name' => Yii::t('app', 'Name'),
			'xp' => Yii::t('app', 'Xp'),
			'character' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('familiarID', $this->familiarID);
		$criteria->compare('active', $this->active);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('xp', $this->xp);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}