<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer active
 * - integer pos1ID
 * - integer pos2ID
 * - integer pos3ID
 * - integer pos4ID
 * - integer pos5ID
 * - integer pos6ID
 * - integer pos7ID
 * - integer pos8ID
 * - integer pos9ID
 * - integer pos10ID
 *
 * - Battleskill pos10
 * - Character character
 * - Battleskill pos9
 * - Battleskill pos1
 * - Battleskill pos2
 * - Battleskill pos3
 * - Battleskill pos4
 * - Battleskill pos5
 * - Battleskill pos6
 * - Battleskill pos7
 * - Battleskill pos8
 * <br>
 * <p>This is the model base class for the table "{{character_skillsets}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterSkillsets".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterSkillsets extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_skillsets}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterSkillsets|CharacterSkillsets', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, active', 'required'),
			array('characterID, active, pos1ID, pos2ID, pos3ID, pos4ID, pos5ID, pos6ID, pos7ID, pos8ID, pos9ID, pos10ID', 'numerical', 'integerOnly'=>true),
			array('pos1ID, pos2ID, pos3ID, pos4ID, pos5ID, pos6ID, pos7ID, pos8ID, pos9ID, pos10ID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, active, pos1ID, pos2ID, pos3ID, pos4ID, pos5ID, pos6ID, pos7ID, pos8ID, pos9ID, pos10ID', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'pos10' => array(self::BELONGS_TO, 'Battleskill', 'pos10ID'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'pos9' => array(self::BELONGS_TO, 'Battleskill', 'pos9ID'),
			'pos1' => array(self::BELONGS_TO, 'Battleskill', 'pos1ID'),
			'pos2' => array(self::BELONGS_TO, 'Battleskill', 'pos2ID'),
			'pos3' => array(self::BELONGS_TO, 'Battleskill', 'pos3ID'),
			'pos4' => array(self::BELONGS_TO, 'Battleskill', 'pos4ID'),
			'pos5' => array(self::BELONGS_TO, 'Battleskill', 'pos5ID'),
			'pos6' => array(self::BELONGS_TO, 'Battleskill', 'pos6ID'),
			'pos7' => array(self::BELONGS_TO, 'Battleskill', 'pos7ID'),
			'pos8' => array(self::BELONGS_TO, 'Battleskill', 'pos8ID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'active' => Yii::t('app', 'Active'),
			'pos1ID' => null,
			'pos2ID' => null,
			'pos3ID' => null,
			'pos4ID' => null,
			'pos5ID' => null,
			'pos6ID' => null,
			'pos7ID' => null,
			'pos8ID' => null,
			'pos9ID' => null,
			'pos10ID' => null,
			'pos10' => null,
			'character' => null,
			'pos9' => null,
			'pos1' => null,
			'pos2' => null,
			'pos3' => null,
			'pos4' => null,
			'pos5' => null,
			'pos6' => null,
			'pos7' => null,
			'pos8' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('active', $this->active);
		$criteria->compare('pos1ID', $this->pos1ID);
		$criteria->compare('pos2ID', $this->pos2ID);
		$criteria->compare('pos3ID', $this->pos3ID);
		$criteria->compare('pos4ID', $this->pos4ID);
		$criteria->compare('pos5ID', $this->pos5ID);
		$criteria->compare('pos6ID', $this->pos6ID);
		$criteria->compare('pos7ID', $this->pos7ID);
		$criteria->compare('pos8ID', $this->pos8ID);
		$criteria->compare('pos9ID', $this->pos9ID);
		$criteria->compare('pos10ID', $this->pos10ID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}