<?php

/**
 * This is the model base class for the table "{{character_items}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterItems".
 *
 * Columns in table "{{character_items}}" available as properties of the model,
 * followed by relations of table "{{character_items}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $characterID
 * @property integer $itemID
 * @property integer $n
 *
 * @property Character $character
 * @property Item $item
 */
abstract class BaseCharacterItems extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{character_items}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CharacterItems|CharacterItems', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('characterID, itemID, n', 'required'),
			array('characterID, itemID, n', 'numerical', 'integerOnly'=>true),
			array('id, characterID, itemID, n', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'item' => array(self::BELONGS_TO, 'Item', 'itemID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'itemID' => null,
			'n' => Yii::t('app', 'N'),
			'character' => null,
			'item' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('itemID', $this->itemID);
		$criteria->compare('n', $this->n);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}