<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer active
 * - integer weaponID
 * - integer offhandID
 * - integer accessoryAID
 * - integer accessoryBID
 * - integer accessoryCID
 *
 * - Item accessoryC
 * - Character character
 * - Item weapon
 * - Item offhand
 * - Item accessoryA
 * - Item accessoryB
 * <br>
 * <p>This is the model base class for the table "{{character_equipments}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterEquipments".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterEquipments extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_equipments}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterEquipments|CharacterEquipments', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, active', 'required'),
			array('characterID, active, weaponID, offhandID, accessoryAID, accessoryBID, accessoryCID', 'numerical', 'integerOnly'=>true),
			array('weaponID, offhandID, accessoryAID, accessoryBID, accessoryCID', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, active, weaponID, offhandID, accessoryAID, accessoryBID, accessoryCID', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'accessoryC' => array(self::BELONGS_TO, 'Item', 'accessoryCID'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'weapon' => array(self::BELONGS_TO, 'Item', 'weaponID'),
			'offhand' => array(self::BELONGS_TO, 'Item', 'offhandID'),
			'accessoryA' => array(self::BELONGS_TO, 'Item', 'accessoryAID'),
			'accessoryB' => array(self::BELONGS_TO, 'Item', 'accessoryBID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'active' => Yii::t('app', 'Active'),
			'weaponID' => null,
			'offhandID' => null,
			'accessoryAID' => null,
			'accessoryBID' => null,
			'accessoryCID' => null,
			'accessoryC' => null,
			'character' => null,
			'weapon' => null,
			'offhand' => null,
			'accessoryA' => null,
			'accessoryB' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('active', $this->active);
		$criteria->compare('weaponID', $this->weaponID);
		$criteria->compare('offhandID', $this->offhandID);
		$criteria->compare('accessoryAID', $this->accessoryAID);
		$criteria->compare('accessoryBID', $this->accessoryBID);
		$criteria->compare('accessoryCID', $this->accessoryCID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}