<?php

/**
 * This is the model base class for the table "{{skill}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Skill".
 *
 * Columns in table "{{skill}}" available as properties of the model,
 * followed by relations of table "{{skill}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $skillType
 * @property string $actionType
 * @property string $battlePhase
 * @property string $subType
 * @property string $specialClass
 * @property integer $charactermodifierID
 * @property integer $costEnergy
 * @property integer $dealsDamage
 * @property string $damageAttackFactor
 * @property integer $damageFixedAmount
 * @property string $damageType
 * @property integer $healing
 * @property integer $createEffect
 * @property integer $effectTurns
 * @property string $effectMsgIncreasedDuration
 * @property string $desc
 * @property string $msgResolved
 *
 * @property CharacterSkills[] $characterSkills
 * @property CharacterSkillsets[] $characterSkillsets
 * @property CharacterSkillsets[] $characterSkillsets1
 * @property CharacterSkillsets[] $characterSkillsets2
 * @property CharacterSkillsets[] $characterSkillsets3
 * @property CharacterSkillsets[] $characterSkillsets4
 * @property CharacterSkillsets[] $characterSkillsets5
 * @property CharacterSkillsets[] $characterSkillsets6
 * @property CharacterSkillsets[] $characterSkillsets7
 * @property CharacterSkillsets[] $characterSkillsets8
 * @property CharacterSkillsets[] $characterSkillsets9
 * @property MonsterSkills[] $monsterSkills
 * @property Charactermodifier $charactermodifier
 * @property Battleeffect $createEffect0
 */
abstract class BaseSkill extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{skill}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Skill|Skills', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, subType, specialClass, effectMsgIncreasedDuration, desc, msgResolved', 'required'),
			array('charactermodifierID, costEnergy, dealsDamage, damageFixedAmount, healing, createEffect, effectTurns', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('skillType', 'length', 'max'=>9),
			array('actionType', 'length', 'max'=>10),
			array('battlePhase', 'length', 'max'=>7),
			array('subType', 'length', 'max'=>20),
			array('specialClass', 'length', 'max'=>40),
			array('damageAttackFactor', 'length', 'max'=>5),
			array('damageType', 'length', 'max'=>8),
			array('skillType, actionType, battlePhase, charactermodifierID, costEnergy, dealsDamage, damageAttackFactor, damageFixedAmount, damageType, healing, createEffect, effectTurns', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, skillType, actionType, battlePhase, subType, specialClass, charactermodifierID, costEnergy, dealsDamage, damageAttackFactor, damageFixedAmount, damageType, healing, createEffect, effectTurns, effectMsgIncreasedDuration, desc, msgResolved', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'characterSkills' => array(self::HAS_MANY, 'CharacterSkills', 'skillID'),
			'characterSkillsets' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos9'),
			'characterSkillsets1' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos10'),
			'characterSkillsets2' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos1'),
			'characterSkillsets3' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos2'),
			'characterSkillsets4' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos3'),
			'characterSkillsets5' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos4'),
			'characterSkillsets6' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos5'),
			'characterSkillsets7' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos6'),
			'characterSkillsets8' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos7'),
			'characterSkillsets9' => array(self::HAS_MANY, 'CharacterSkillsets', 'pos8'),
			'monsterSkills' => array(self::HAS_MANY, 'MonsterSkills', 'skillID'),
			'charactermodifier' => array(self::BELONGS_TO, 'Charactermodifier', 'charactermodifierID'),
			'createEffect0' => array(self::BELONGS_TO, 'Battleeffect', 'createEffect'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'skillType' => Yii::t('app', 'Skill Type'),
			'actionType' => Yii::t('app', 'Action Type'),
			'battlePhase' => Yii::t('app', 'Battle Phase'),
			'subType' => Yii::t('app', 'Sub Type'),
			'specialClass' => Yii::t('app', 'Special Class'),
			'charactermodifierID' => null,
			'costEnergy' => Yii::t('app', 'Cost Energy'),
			'dealsDamage' => Yii::t('app', 'Deals Damage'),
			'damageAttackFactor' => Yii::t('app', 'Damage Attack Factor'),
			'damageFixedAmount' => Yii::t('app', 'Damage Fixed Amount'),
			'damageType' => Yii::t('app', 'Damage Type'),
			'healing' => Yii::t('app', 'Healing'),
			'createEffect' => null,
			'effectTurns' => Yii::t('app', 'Effect Turns'),
			'effectMsgIncreasedDuration' => Yii::t('app', 'Effect Msg Increased Duration'),
			'desc' => Yii::t('app', 'Desc'),
			'msgResolved' => Yii::t('app', 'Msg Resolved'),
			'characterSkills' => null,
			'characterSkillsets' => null,
			'characterSkillsets1' => null,
			'characterSkillsets2' => null,
			'characterSkillsets3' => null,
			'characterSkillsets4' => null,
			'characterSkillsets5' => null,
			'characterSkillsets6' => null,
			'characterSkillsets7' => null,
			'characterSkillsets8' => null,
			'characterSkillsets9' => null,
			'monsterSkills' => null,
			'charactermodifier' => null,
			'createEffect0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('skillType', $this->skillType, true);
		$criteria->compare('actionType', $this->actionType, true);
		$criteria->compare('battlePhase', $this->battlePhase, true);
		$criteria->compare('subType', $this->subType, true);
		$criteria->compare('specialClass', $this->specialClass, true);
		$criteria->compare('charactermodifierID', $this->charactermodifierID);
		$criteria->compare('costEnergy', $this->costEnergy);
		$criteria->compare('dealsDamage', $this->dealsDamage);
		$criteria->compare('damageAttackFactor', $this->damageAttackFactor, true);
		$criteria->compare('damageFixedAmount', $this->damageFixedAmount);
		$criteria->compare('damageType', $this->damageType, true);
		$criteria->compare('healing', $this->healing);
		$criteria->compare('createEffect', $this->createEffect);
		$criteria->compare('effectTurns', $this->effectTurns);
		$criteria->compare('effectMsgIncreasedDuration', $this->effectMsgIncreasedDuration, true);
		$criteria->compare('desc', $this->desc, true);
		$criteria->compare('msgResolved', $this->msgResolved, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}