<?php

/**
 * This is the model base class for the table "{{character_familiars}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterFamiliars".
 *
 * Columns in table "{{character_familiars}}" available as properties of the model,
 * followed by relations of table "{{character_familiars}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $characterID
 * @property integer $familiarID
 * @property integer $active
 * @property string $name
 * @property integer $xp
 *
 * @property Character $character
 */
abstract class BaseCharacterFamiliars extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{character_familiars}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CharacterFamiliars|CharacterFamiliars', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('characterID, familiarID, name, xp', 'required'),
			array('characterID, familiarID, active, xp', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, familiarID, active, name, xp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'familiarID' => Yii::t('app', 'Familiar'),
			'active' => Yii::t('app', 'Active'),
			'name' => Yii::t('app', 'Name'),
			'xp' => Yii::t('app', 'Xp'),
			'character' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('familiarID', $this->familiarID);
		$criteria->compare('active', $this->active);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('xp', $this->xp);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}