<?php

/**
 * This is the model base class for the table "{{skillset}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Skillset".
 *
 * Columns in table "{{skillset}}" available as properties of the model,
 * followed by relations of table "{{skillset}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $characterID
 * @property integer $active
 * @property integer $pos1
 * @property integer $pos2
 * @property integer $pos3
 * @property integer $pos4
 * @property integer $pos5
 * @property integer $pos6
 * @property integer $pos7
 * @property integer $pos8
 * @property integer $pos9
 * @property integer $pos10
 *
 * @property Skill $pos100
 * @property Character $character
 * @property Skill $pos90
 * @property Skill $pos11
 * @property Skill $pos20
 * @property Skill $pos30
 * @property Skill $pos40
 * @property Skill $pos50
 * @property Skill $pos60
 * @property Skill $pos70
 * @property Skill $pos80
 */
abstract class BaseSkillset extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{skillset}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Skillset|Skillsets', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('characterID, active, pos1, pos2, pos3, pos4, pos5, pos6, pos7, pos8, pos9, pos10', 'required'),
			array('characterID, active, pos1, pos2, pos3, pos4, pos5, pos6, pos7, pos8, pos9, pos10', 'numerical', 'integerOnly'=>true),
			array('id, characterID, active, pos1, pos2, pos3, pos4, pos5, pos6, pos7, pos8, pos9, pos10', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pos100' => array(self::BELONGS_TO, 'Skill', 'pos10'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'pos90' => array(self::BELONGS_TO, 'Skill', 'pos9'),
			'pos11' => array(self::BELONGS_TO, 'Skill', 'pos1'),
			'pos20' => array(self::BELONGS_TO, 'Skill', 'pos2'),
			'pos30' => array(self::BELONGS_TO, 'Skill', 'pos3'),
			'pos40' => array(self::BELONGS_TO, 'Skill', 'pos4'),
			'pos50' => array(self::BELONGS_TO, 'Skill', 'pos5'),
			'pos60' => array(self::BELONGS_TO, 'Skill', 'pos6'),
			'pos70' => array(self::BELONGS_TO, 'Skill', 'pos7'),
			'pos80' => array(self::BELONGS_TO, 'Skill', 'pos8'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'active' => Yii::t('app', 'Active'),
			'pos1' => null,
			'pos2' => null,
			'pos3' => null,
			'pos4' => null,
			'pos5' => null,
			'pos6' => null,
			'pos7' => null,
			'pos8' => null,
			'pos9' => null,
			'pos10' => null,
			'pos100' => null,
			'character' => null,
			'pos90' => null,
			'pos11' => null,
			'pos20' => null,
			'pos30' => null,
			'pos40' => null,
			'pos50' => null,
			'pos60' => null,
			'pos70' => null,
			'pos80' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('active', $this->active);
		$criteria->compare('pos1', $this->pos1);
		$criteria->compare('pos2', $this->pos2);
		$criteria->compare('pos3', $this->pos3);
		$criteria->compare('pos4', $this->pos4);
		$criteria->compare('pos5', $this->pos5);
		$criteria->compare('pos6', $this->pos6);
		$criteria->compare('pos7', $this->pos7);
		$criteria->compare('pos8', $this->pos8);
		$criteria->compare('pos9', $this->pos9);
		$criteria->compare('pos10', $this->pos10);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}