<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer contactID
 * - string name
 * - integer befriendable
 * - integer befriended
 * - integer bribable
 * - integer bribed
 * - integer seducible
 * - integer seduced
 *
 * - Character character
 * - Contact contact
 * <br>
 * <p>This is the model base class for the table "{{character_contacts}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterContacts".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterContacts extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_contacts}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterContacts|CharacterContacts', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'name';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, contactID, name', 'required'),
			array('characterID, contactID, befriendable, befriended, bribable, bribed, seducible, seduced', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('befriendable, befriended, bribable, bribed, seducible, seduced', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, contactID, name, befriendable, befriended, bribable, bribed, seducible, seduced', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'contact' => array(self::BELONGS_TO, 'Contact', 'contactID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'contactID' => null,
			'name' => Yii::t('app', 'Name'),
			'befriendable' => Yii::t('app', 'Befriendable'),
			'befriended' => Yii::t('app', 'Befriended'),
			'bribable' => Yii::t('app', 'Bribable'),
			'bribed' => Yii::t('app', 'Bribed'),
			'seducible' => Yii::t('app', 'Seducible'),
			'seduced' => Yii::t('app', 'Seduced'),
			'character' => null,
			'contact' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('contactID', $this->contactID);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('befriendable', $this->befriendable);
		$criteria->compare('befriended', $this->befriended);
		$criteria->compare('bribable', $this->bribable);
		$criteria->compare('bribed', $this->bribed);
		$criteria->compare('seducible', $this->seducible);
		$criteria->compare('seduced', $this->seduced);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}