<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - string type
 * - integer combatantAID
 * - integer combatantBID
 * - string state
 * - string winnerType
 * - integer winnerID
 * - string objectState
 *
 * <br>
 * <p>This is the model base class for the table "{{battle}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Battle".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseBattle extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @see http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{battle}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'Battle|Battles', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'type';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('combatantAID, combatantBID, winnerID, objectState', 'required'),
			array('combatantAID, combatantBID, winnerID', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>7),
			array('state', 'length', 'max'=>8),
			array('winnerType', 'length', 'max'=>9),
			array('type, state, winnerType', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type, combatantAID, combatantBID, state, winnerType, winnerID, objectState', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
			'combatantAID' => Yii::t('app', 'Combatant Aid'),
			'combatantBID' => Yii::t('app', 'Combatant Bid'),
			'state' => Yii::t('app', 'State'),
			'winnerType' => Yii::t('app', 'Winner Type'),
			'winnerID' => Yii::t('app', 'Winner'),
			'objectState' => Yii::t('app', 'Object State'),
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('combatantAID', $this->combatantAID);
		$criteria->compare('combatantBID', $this->combatantBID);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('winnerType', $this->winnerType, true);
		$criteria->compare('winnerID', $this->winnerID);
		$criteria->compare('objectState', $this->objectState, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}