<?php

/**
 * This is the model base class for the table "{{monster_skills}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MonsterSkills".
 *
 * Columns in table "{{monster_skills}}" available as properties of the model,
 * followed by relations of table "{{monster_skills}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $monsterID
 * @property integer $skillID
 * @property double $prob
 *
 * @property Skill $skill
 * @property Monster $monster
 */
abstract class BaseMonsterSkills extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{monster_skills}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MonsterSkills|MonsterSkills', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('monsterID, skillID, prob', 'required'),
			array('monsterID, skillID', 'numerical', 'integerOnly'=>true),
			array('prob', 'numerical'),
			array('id, monsterID, skillID, prob', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'skill' => array(self::BELONGS_TO, 'Skill', 'skillID'),
			'monster' => array(self::BELONGS_TO, 'Monster', 'monsterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'monsterID' => null,
			'skillID' => null,
			'prob' => Yii::t('app', 'Prob'),
			'skill' => null,
			'monster' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('monsterID', $this->monsterID);
		$criteria->compare('skillID', $this->skillID);
		$criteria->compare('prob', $this->prob);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}