<?php

/**
 * This is the model base class for the table "{{area_monsters}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AreaMonsters".
 *
 * Columns in table "{{area_monsters}}" available as properties of the model,
 * followed by relations of table "{{area_monsters}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $areaID
 * @property integer $monsterID
 * @property string $prob
 *
 * @property Area $area
 * @property Monster $monster
 */
abstract class BaseAreaMonsters extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{area_monsters}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AreaMonsters|AreaMonsters', $n);
	}

	public static function representingColumn() {
		return 'prob';
	}

	public function rules() {
		return array(
			array('areaID, monsterID', 'required'),
			array('areaID, monsterID', 'numerical', 'integerOnly'=>true),
			array('prob', 'length', 'max'=>5),
			array('prob', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, areaID, monsterID, prob', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'area' => array(self::BELONGS_TO, 'Area', 'areaID'),
			'monster' => array(self::BELONGS_TO, 'Monster', 'monsterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'areaID' => null,
			'monsterID' => null,
			'prob' => Yii::t('app', 'Prob'),
			'area' => null,
			'monster' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('areaID', $this->areaID);
		$criteria->compare('monsterID', $this->monsterID);
		$criteria->compare('prob', $this->prob, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}