<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer questID
 * - string state
 * - integer visible
 * - string questState
 *
 * - Character character
 * - Quest quest
 * <br>
 * <p>This is the model base class for the table "{{character_quests}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterQuests".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterQuests extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_quests}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterQuests|CharacterQuests', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'state';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, questID', 'required'),
			array('characterID, questID, visible', 'numerical', 'integerOnly'=>true),
			array('state', 'length', 'max'=>11),
			array('questState', 'safe'),
			array('state, visible, questState', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, questID, state, visible, questState', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'quest' => array(self::BELONGS_TO, 'Quest', 'questID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'questID' => null,
			'state' => Yii::t('app', 'State'),
			'visible' => Yii::t('app', 'Visible'),
			'questState' => Yii::t('app', 'Quest State'),
			'character' => null,
			'quest' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('questID', $this->questID);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('visible', $this->visible);
		$criteria->compare('questState', $this->questState, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}