<?php

/**
 * This is the model base class for the table "{{monster_items}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MonsterItems".
 *
 * Columns in table "{{monster_items}}" available as properties of the model,
 * followed by relations of table "{{monster_items}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $monsterID
 * @property integer $itemID
 * @property double $prob
 *
 * @property Item $item
 * @property Monster $monster
 */
abstract class BaseMonsterItems extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{monster_items}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MonsterItems|MonsterItems', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('monsterID, itemID, prob', 'required'),
			array('monsterID, itemID', 'numerical', 'integerOnly'=>true),
			array('prob', 'numerical'),
			array('id, monsterID, itemID, prob', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'item' => array(self::BELONGS_TO, 'Item', 'itemID'),
			'monster' => array(self::BELONGS_TO, 'Monster', 'monsterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'monsterID' => null,
			'itemID' => null,
			'prob' => Yii::t('app', 'Prob'),
			'item' => null,
			'monster' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('monsterID', $this->monsterID);
		$criteria->compare('itemID', $this->itemID);
		$criteria->compare('prob', $this->prob);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}