<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer characterID
 * - integer active
 * - integer weapon
 * - integer offhand
 * - integer accessoryA
 * - integer accessoryB
 * - integer accessoryC
 *
 * - Item accessoryC0
 * - Character character
 * - Item weapon0
 * - Item offhand0
 * - Item accessoryA0
 * - Item accessoryB0
 * <br>
 * <p>This is the model base class for the table "{{character_equipments}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterEquipments".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseCharacterEquipments extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @see http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{character_equipments}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'CharacterEquipments|CharacterEquipments', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('characterID, active', 'required'),
			array('characterID, active, weapon, offhand, accessoryA, accessoryB, accessoryC', 'numerical', 'integerOnly'=>true),
			array('weapon, offhand, accessoryA, accessoryB, accessoryC', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, characterID, active, weapon, offhand, accessoryA, accessoryB, accessoryC', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'accessoryC0' => array(self::BELONGS_TO, 'Item', 'accessoryC'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
			'weapon0' => array(self::BELONGS_TO, 'Item', 'weapon'),
			'offhand0' => array(self::BELONGS_TO, 'Item', 'offhand'),
			'accessoryA0' => array(self::BELONGS_TO, 'Item', 'accessoryA'),
			'accessoryB0' => array(self::BELONGS_TO, 'Item', 'accessoryB'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'active' => Yii::t('app', 'Active'),
			'weapon' => null,
			'offhand' => null,
			'accessoryA' => null,
			'accessoryB' => null,
			'accessoryC' => null,
			'accessoryC0' => null,
			'character' => null,
			'weapon0' => null,
			'offhand0' => null,
			'accessoryA0' => null,
			'accessoryB0' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('active', $this->active);
		$criteria->compare('weapon', $this->weapon);
		$criteria->compare('offhand', $this->offhand);
		$criteria->compare('accessoryA', $this->accessoryA);
		$criteria->compare('accessoryB', $this->accessoryB);
		$criteria->compare('accessoryC', $this->accessoryC);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}