<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer item1ID
 * - integer item2ID
 * - integer itemResultID
 * - integer costCash
 * - integer costFavours
 * - integer costKudos
 * - integer costsTurn
 *
 * - CharacterRecipes characterRecipes
 * - Item item1
 * - Item item2
 * - Item itemResult
 * <br>
 * <p>This is the model base class for the table "{{recipe}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Recipe".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseRecipe extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @link http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{recipe}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'Recipe|Recipes', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('item1ID, item2ID, itemResultID', 'required'),
			array('item1ID, item2ID, itemResultID, costCash, costFavours, costKudos, costsTurn', 'numerical', 'integerOnly'=>true),
			array('costCash, costFavours, costKudos, costsTurn', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item1ID, item2ID, itemResultID, costCash, costFavours, costKudos, costsTurn', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'characterRecipes' => array(self::HAS_MANY, 'CharacterRecipes', 'recipeID'),
			'item1' => array(self::BELONGS_TO, 'Item', 'item1ID'),
			'item2' => array(self::BELONGS_TO, 'Item', 'item2ID'),
			'itemResult' => array(self::BELONGS_TO, 'Item', 'itemResultID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item1ID' => null,
			'item2ID' => null,
			'itemResultID' => null,
			'costCash' => Yii::t('app', 'Cost Cash'),
			'costFavours' => Yii::t('app', 'Cost Favours'),
			'costKudos' => Yii::t('app', 'Cost Kudos'),
			'costsTurn' => Yii::t('app', 'Costs Turn'),
			'characterRecipes' => null,
			'item1' => null,
			'item2' => null,
			'itemResult' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item1ID', $this->item1ID);
		$criteria->compare('item2ID', $this->item2ID);
		$criteria->compare('itemResultID', $this->itemResultID);
		$criteria->compare('costCash', $this->costCash);
		$criteria->compare('costFavours', $this->costFavours);
		$criteria->compare('costKudos', $this->costKudos);
		$criteria->compare('costsTurn', $this->costsTurn);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}