<?php

/**
 * Properties and related Models:
 *
 * - integer id
 * - integer fromEncounterID
 * - integer toEncounterID
 *
 * - AreaEncounters toEncounter
 * - AreaEncounters fromEncounter
 * <br>
 * <p>This is the model base class for the table "{{encounter_encounters}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EncounterEncounters".</p>
 * <p>Beware: decimals and floats can show up as strings in the attribute list</p>
 *
 * @package System.Models.Base
 */
abstract class BaseEncounterEncounters extends GxActiveRecord {

    /**
     * Factory method to get Model objects
     * @see http://www.yiiframework.com/doc/api/CModel
     * @param string $className
     * @return CModel
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	/**
	 * Returns the name of the table that this model is based on
	 * @return string
	 */
	public function tableName() {
		return '{{encounter_encounters}}';
	}

	/**
	 * Returns a label for this Model (singular or plural) based on $n
	 * @param int $n default 1
	 * @return string
	 */
	public static function label($n = 1) {
		return Yii::t('app', 'EncounterEncounters|EncounterEncounters', $n);
	}

	/**
	 * Returns a string or array of strings
	 * Not quite sure what this is for, though
	 * @return mixed
	 */
	public static function representingColumn() {
		return 'id';
	}

	/**
	 * Returns an array with rules that specify valid Model data
	 * @return array
	 */
	public function rules() {
		return array(
			array('fromEncounterID, toEncounterID', 'required'),
			array('fromEncounterID, toEncounterID', 'numerical', 'integerOnly'=>true),
			array('id, fromEncounterID, toEncounterID', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * Returns an array of the form 
	 * "relationAttributeName" => array(BELONGS_TO|HAS_MANY, foreign Model, foreign attribute (key))
	 * @return array
	 */
	public function relations() {
		return array(
			'toEncounter' => array(self::BELONGS_TO, 'AreaEncounters', 'toEncounterID'),
			'fromEncounter' => array(self::BELONGS_TO, 'AreaEncounters', 'fromEncounterID'),
		);
	}

	/**
	 * Returns an array that specifies pivotModel configurations
	 * @return array
	 */
	public function pivotModels() {
		return array(
		);
	}

	/**
	 * Returns an array with attributeLabels for the Model's attributes
	 * @return array
	 */
	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fromEncounterID' => null,
			'toEncounterID' => null,
			'toEncounter' => null,
			'fromEncounter' => null,
		);
	}

	/**
	 * Returns a CActiveDataProvider, fed with search criteria based
	 * on the object's attributes
	 * @return CActiveDataProvider
	 * @link http://www.yiiframework.com/doc/api/CActiveDataProvider
	 */
	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fromEncounterID', $this->fromEncounterID);
		$criteria->compare('toEncounterID', $this->toEncounterID);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}