<?php

/**
 * This is the model base class for the table "{{character_effects}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CharacterEffects".
 *
 * Columns in table "{{character_effects}}" available as properties of the model,
 * followed by relations of table "{{character_effects}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $characterID
 * @property integer $effectID
 * @property integer $turns
 *
 * @property Effect $effect
 * @property Character $character
 */
abstract class BaseCharacterEffects extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{character_effects}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CharacterEffects|CharacterEffects', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('characterID, effectID, turns', 'required'),
			array('characterID, effectID, turns', 'numerical', 'integerOnly'=>true),
			array('id, characterID, effectID, turns', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'effect' => array(self::BELONGS_TO, 'Effect', 'effectID'),
			'character' => array(self::BELONGS_TO, 'Character', 'characterID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'characterID' => null,
			'effectID' => null,
			'turns' => Yii::t('app', 'Turns'),
			'effect' => null,
			'character' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('characterID', $this->characterID);
		$criteria->compare('effectID', $this->effectID);
		$criteria->compare('turns', $this->turns);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}